import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: ["intro", { dirName: "plugins", type: "autogenerated" }],
};

export default sidebars;
