name: Node CI

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    env:
      GIT_USER: github-actions[bot]
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - name: SETUP_NODE_${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: BEFORE_SCRIPT
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: INSTALL_PACKAGES
        run: pnpm install --frozen-lockfile
      - name: BUILD
        run: pnpm --filter "@gracefullight/docusaurus-plugin-docs" run build
      - name: DEPLOY
        run: pnpm --filter "@gracefullight/docusaurus-plugin-docs" run deploy
