name: Deploy Docs

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      # Build the Docusaurus site in apps/docs
      # The previous filter didn't match any workspace package, so no build ran.
      # Use the actual package name to ensure the build step executes.
      - run: pnpm --filter "@gracefullight/docusaurus-plugin-docs" build
      - uses: actions/upload-pages-artifact@v4
        with:
          path: apps/docs/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # Use the reserved GitHub Pages environment without URL expression
    # to avoid job-level expression context limitations.
    # environment: github-pages
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
